# Cryst, chapter 1
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("cryst01.tst");

# doc/introduction.xml:33-36
gap> LoadPackage( "cryst" ); 
true

#
gap> STOP_TEST("cryst01.tst", 1);
