#!/bin/sh

# before running this script, edit date and version in
# Changelog, PackageInfo.g, etc/VERSION, etc/make_tar
# etc/changelog.html, doc/manual.tex

./make_tar

cp VERSION                 ~/WWW/gap/Cryst
cp changelog.html          ~/WWW/gap/Cryst
mv *.tar.gz                ~/WWW/gap/Cryst
cp ../PackageInfo.g        ~/WWW/gap/Cryst
grep -v svg ../README.md > ~/WWW/gap/Cryst/README.cryst

cd ~/WWW/gap; ./get_html; chmod -R a+r *

