#!/bin/tcsh

# remove old archive
rm cryst.zoo

# goto <gaproot>/pkg
cd ../..

# first the binary files
echo "\!BINARY\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.dvi

# then the text files
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.tex
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.bbl
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.six
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.mst
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.ps
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/cryst.tex
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/preface.tex
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/make_doc
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/init.g
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/read.g
#echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/README
foreach file (cryst/gap/*.g[di])
  echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo $file
end
foreach file (cryst/grp/spacegrp.*)
  echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo $file
end
foreach file (cryst/htm/*.htm)
  echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo $file
end

# check result
cd cryst/etc
zoo -list cryst.zoo

