#!/bin/sh

# remove old archive
rm cryst.zoo

# goto <gaproot>/pkg
cd ../..

# first the binary files
echo "\!BINARY\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.dvi
echo "\!BINARY\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.pdf

# then the text files
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.tex
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.bbl
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.six
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.lab
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.mst
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/manual.ps
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/introduction.tex
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/cryst.tex
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/doc/make_doc
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/init.g
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/read.g
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/README
echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo cryst/Changelog
for file in cryst/gap/*.g[di] ; do
  echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo $file
done
for file in cryst/grp/spacegrp.* ; do
  echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo $file
done
for file in cryst/htm/*.htm ; do
  echo "\!TEXT\!\n/END" | zoo ach cryst/etc/cryst.zoo $file
done

# check result
cd cryst/etc
zoo -list cryst.zoo

