#!/bin/sh
set -e

echo "TeXing documentation"
# delete old stuff to avoid spurious or "hidden errors" caused by their presence
rm -f manual.{aux,bbl,blg,dvi,idx,ilg,ind,lab,log,pdf,ps,six,toc}
tex manual
../../../doc/manualindex manual
tex manual

echo "Creating PDF version"
pdftex manual; pdftex manual

echo "Creating HTML documentation"
mkdir -p ../htm
../../../etc/convert.pl -c -i -u -n cryst . ../htm
