#!/bin/sh
set -e

echo "TeXing documentation"
rm -f manual.aux manual.dvi manual.idx manual.ilg manual.ind manual.lab manual.log manual.six manual.toc
tex manual
../../../doc/manualindex manual
tex manual

echo "Creating PDF version"
pdftex manual; pdftex manual

echo "Creating HTML documentation"
mkdir -p ../htm
../../../etc/convert.pl -c -i -u -n cryst . ../htm
